modLoader="javafml"
loaderVersion="[1,)"
license="LicenseRef-AMALGAM-Proprietary"

[[mods]]
modId="asterion"
version="${version}"
displayName="Asterion"
authors="Kronoz, DarkFox"
description='''Descend into an infinite living labyrinth, explore its flooded catacombs, and survive the Minotaur at its heart.'''
logoFile="assets/asterion/icon.png"

[[dependencies.asterion]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.asterion]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.asterion]]
modId="amnetic"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.asterion]]
modId="geckolib"
mandatory=true
versionRange="[${geckolib_version},)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="asterion.mixins.json"
