org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
minecraft_version=1.21.1
loader_version=0.18.4
mod_version=1.2.2
maven_group=net.krodark
archives_base_name=Asterion
fabric_version=0.116.8+1.21.1
geckolib_version=4.9.2
modmenu_version=11.0.4
veil_version=4.5.0
jei_version=19.21.2.313
rei_version=16.0.799
architectury_version=13.0.8
cloth_config_version=15.0.140
jade_version=15.10.0+fabric
neoforge_version=21.1.248
forgified_fabric_api_version=0.116.15+2.3.5+1.21.1
