modLoader="javafml"
loaderVersion="[64,)"
license="All Rights Reserved"

[[mods]]
modId="asterion"
version="${version}"
displayName="Asterion"
description='''The Labyrinth dimension and its creatures, native on Forge.'''

[[dependencies.asterion]]
modId="forge"
mandatory=true
versionRange="[64,)"
ordering="NONE"
side="BOTH"

[[dependencies.asterion]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
