modLoader="javafml"
loaderVersion="[4,)"
license="All-Rights-Reserved"
[[mods]]
modId="amnetic"
version="1.0.0-asterion.9+1.21.1"
displayName="Amnetic"
description="Amnetic renderer with the Asterion native NeoForge lifecycle adapter."
[[mixins]]
config="amnetic.mixins.json"
[[dependencies.amnetic]]
modId="neoforge"
type="required"
versionRange="[21.1.248,)"
side="BOTH"
[[dependencies.amnetic]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
side="BOTH"
[[dependencies.amnetic]]
modId="fabric_api"
type="required"
versionRange="[0.116.15,)"
ordering="BEFORE"
side="CLIENT"
