modLoader="javafml"
loaderVersion="[1,)"
license="LicenseRef-AMALGAM-Proprietary"

[[mixins]]
config="asterion.mixins.json"

[[mods]]
modId="asterion"
version="${version}"
displayName="Asterion"
description='''Descend into an infinite living labyrinth, explore its flooded catacombs, and survive the Minotaur at its heart.'''
authors="Kronoz, DarkFox"

[[dependencies.asterion]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.asterion]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.asterion]]
modId="fabric_api"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.asterion]]
modId="geckolib"
type="required"
versionRange="[5.5.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.asterion]]
modId="amnetic"
type="required"
versionRange="[1.0-SNAPSHOT,)"
ordering="AFTER"
side="CLIENT"
