modLoader="javafml"
loaderVersion="[4,)"
license="LicenseRef-AMALGAM-Proprietary"

[[mods]]
modId="asterion"
version="${version}"
displayName="Asterion"
authors="Kronoz, DarkFox"
description='''Descend into an infinite living labyrinth, explore its flooded catacombs, and survive the Minotaur at its heart.'''
logoFile="assets/asterion/icon.png"

[[mixins]]
config="asterion.mixins.json"

[[mixins]]
config="asterion.neoforge.mixins.json"

[[dependencies.asterion]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.asterion]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.asterion]]
modId="amnetic"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.asterion]]
modId="geckolib"
type="required"
versionRange="[${geckolib_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.asterion]]
modId="fabric_api"
type="required"
versionRange="[0.116.15,)"
ordering="BEFORE"
side="BOTH"

